### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ACGaming**

### CODE REVIEW

**Comment by SocraticPhoenix** [comment]
In order for this translation to actually work, the code itself will have to be changed, since the code is were the names of the items are set. This is an important first step (and thanks!), but before I accept this pull request, I first need to implement a system that allows translations in the code too.

**Comment by SocraticPhoenix** [comment]
Figured out how to do the translations! Not going to be as hard as I thought... I'll publish it when it's done, along with a guide on how to do translations...

**Comment by SocraticPhoenix** [comment]
@ACGaming 
I've got the translations working. In addition to the file you've already translated, one with the same name (but different contents) needs to go [here](https://github.com/SocraticPhoenix/Randores/tree/master/src/main/resources/com/gmail/socraticphoenix/forge/randore/resource/lang). Look at the en_US one for the keys and messages. Then, add the file name to [this file](https://github.com/SocraticPhoenix/Randores/blob/master/src/main/resources/com/gmail/socraticphoenix/forge/randore/resource/ab_dict.txt). Also, thanks very very much for doing translations!

**Comment by ACGaming** [comment]
Done!

**Comment by SocraticPhoenix** [comment]
@ACGaming 
Sorry to bother you, but I've been updating the mod, and with updates come new translations. There are 4 more lines in [this](https://github.com/SocraticPhoenix/Randores/blob/master/src/main/resources/com/gmail/socraticphoenix/forge/randore/resource/lang/en_US.lang) file... After "translations block 1." The last three lines are translations, but the "randores.name.format=${name} ${item}" line is not. It specifies how the name of an item should be constructed. For example, if the ore name was "Iron" and the Item was "Axe" the format "${name} ${item}" would create "Iron Axe," while the format "${item}-${name}" would produce "Axe-Iron." This just adds support for languages that don't format the names the same as english... I don't know If you'll need to change it or not.

**Pull request merged**
